# Generated by Django 4.2.8 on 2023-12-23 10:05

import assembler.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_hack_l_file', models.FileField(upload_to=assembler.models.user_directory_path)),
                ('uploaded_ml_file', models.FileField(upload_to=assembler.models.user_directory_path)),
                ('upload_date', models.DateTimeField(verbose_name='Upload Date and Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
