# Generated by Django 4.2.8 on 2023-12-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='uploaded_ml_file',
        ),
    ]
